apiVersion: v1
kind: Service
metadata:
  name: fire-back-nodeport
spec:
  type: NodePort
  selector:
    app: fireback
  ports:
    - name: fireback
      protocol: TCP
      port: 80
      targetPort: 80